#Genera un codigo que indique las vocales de un texto:
def contar_vocales(texto):
    vocales = 'aeiouAEIOU'
    contador = 0
    for letra in texto:
        if letra in vocales:
            contador += 1
    return contador
input_texto = """Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ac metus urna. Etiam efficitur lacinia diam at rutrum. Mauris vitae sollicitudin metus. Aenean magna tortor, malesuada at erat eget, ullamcorper imperdiet nibh. Duis tempor lorem vel quam posuere, consectetur convallis dui tincidunt. Praesent gravida leo nec erat rhoncus interdum. Aliquam luctus sit amet ante ut tincidunt. Donec sit amet magna vitae libero luctus auctor. Nunc magna augue, maximus at blandit vitae, lobortis sed purus. Suspendisse scelerisque mauris non dui venenatis porta. Etiam faucibus, diam quis semper gravida, mauris velit commodo libero, nec efficitur libero mi a quam. Praesent vitae ullamcorper libero. Phasellus id felis sed quam tincidunt pretium non sed odio. Pellentesque nec lacus consequat, cursus lacus vestibulum, euismod urna. Fusce porttitor massa in tortor tempor, in suscipit justo fringilla. Ut facilisis eros sit amet massa scelerisque auctor non non quam.

Phasellus ut elit ac nisi aliquet blandit. Phasellus porttitor elementum orci id malesuada. Vivamus viverra porttitor urna, vitae egestas purus ultrices sit amet. Nullam lobortis tristique velit, non venenatis magna vehicula a. Morbi bibendum eleifend nisi. Etiam euismod odio sed libero tincidunt, a aliquet sem sagittis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nam sed turpis id nibh vestibulum imperdiet. Nulla nec est maximus, ornare urna eu, congue metus.

Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque in molestie dolor, eu sagittis quam. Morbi fermentum lobortis odio, id feugiat turpis eleifend vitae. Etiam sodales aliquam turpis. Vestibulum auctor arcu in ipsum auctor, et lacinia diam rutrum. Curabitur in consequat arcu. Fusce vel nibh ex. Sed quis fringilla lorem, eu hendrerit elit. Ut placerat nisi purus, rhoncus posuere diam ullamcorper et. Duis nunc erat, finibus eget tincidunt ac, iaculis vel nisl. Etiam dictum, turpis a ultrices porta, quam enim posuere elit, ut mattis nisi nisi eu magna. Nunc eros mauris, aliquam vitae cursus sed, rutrum feugiat mi. Curabitur ultrices eros vitae nisl congue, eu finibus elit tincidunt.

Duis posuere eros eu velit luctus consequat. Donec luctus augue est, in tincidunt diam lacinia sit amet. Duis finibus luctus nisl vitae volutpat. Aliquam tristique tincidunt hendrerit. Praesent sed ligula maximus, rhoncus quam sit amet, mollis quam. Donec vehicula augue in venenatis finibus. Suspendisse nec erat in massa tincidunt faucibus id sed nisi. Aenean porttitor mauris dolor, at bibendum urna rhoncus hendrerit. Duis turpis urna, pharetra et sagittis condimentum, tincidunt eu lacus. Sed condimentum tellus nec tristique porta. Etiam et sem eget ex accumsan facilisis quis ac magna. Morbi lacinia neque id lacus interdum congue. Nam in felis ipsum. Quisque in ornare enim. Cras in dapibus erat. Maecenas sodales nibh sem, sit amet consectetur justo gravida ac.

Proin fermentum nulla turpis, vitae hendrerit ligula fermentum eget. Donec congue, magna ac posuere molestie, libero urna aliquam ante, sed condimentum dui purus sit amet est. Ut venenatis suscipit libero, vitae accumsan arcu malesuada ac. Aliquam sit amet quam eu quam tincidunt tincidunt. Proin mollis quam at libero placerat, vel ornare diam consequat. Curabitur gravida tellus eu nulla ullamcorper tincidunt. Nulla ultrices et lacus nec gravida. Curabitur id justo interdum, placerat urna eu, dictum ipsum. Proin vitae ipsum consequat, porttitor dui vitae, ultricies nulla. Maecenas ultrices turpis eu commodo laoreet.

Mauris non augue non augue convallis pulvinar ac sit amet dui. Pellentesque dictum dapibus aliquam. Pellentesque dapibus sagittis dui, eu blandit nulla scelerisque condimentum. Aenean vitae eleifend risus. Proin ac ligula volutpat, placerat tortor vitae, sodales eros. Morbi sed dictum elit. Aliquam nibh est, finibus sit amet ante non, porta efficitur nunc. Praesent tempor placerat dui vel sagittis. Duis ornare porttitor arcu vitae venenatis. Proin consequat massa id leo bibendum, vel sagittis lorem luctus. Aliquam augue ante, porta non efficitur id, malesuada nec dolor. Suspendisse condimentum mauris quis scelerisque malesuada.

Cras vel ante quis libero maximus pulvinar id vel orci. Vestibulum vel sollicitudin nibh. Nullam porttitor erat quis erat feugiat efficitur. Morbi posuere, neque eu venenatis vulputate, eros magna dapibus metus, ut porttitor orci enim eu eros. Nam sapien nisl, lobortis eu quam et, efficitur elementum felis. Aliquam lobortis ligula vel rhoncus auctor. Aliquam hendrerit, justo vitae vestibulum imperdiet, lectus sapien feugiat justo, eget maximus nibh nibh sit amet est. Sed risus mi, faucibus ut metus et, sollicitudin placerat nulla. Nunc sit amet elementum erat.

Proin vestibulum ac nisl non finibus. Vestibulum metus urna, rutrum et nulla vitae, dapibus vulputate libero. Morbi dui nunc, mattis at enim aliquet, scelerisque mollis diam. Vestibulum non lobortis erat. Praesent tempus vulputate dictum. Quisque placerat ex at lacus varius fringilla. In rutrum nulla ut nulla blandit efficitur. Curabitur commodo aliquet tempus. Etiam sollicitudin ultrices lacus quis lacinia. Etiam id viverra velit. Proin faucibus sit amet velit nec tincidunt.

Mauris a dolor congue, ornare nisl vitae, consequat dui. Phasellus velit odio, maximus eget ex at, pulvinar auctor orci. Etiam dapibus efficitur turpis ut fermentum. Donec et nunc vel urna mollis sollicitudin. Quisque accumsan sagittis augue, tempus pellentesque justo condimentum quis. Nunc velit arcu, fringilla non sagittis vel, semper vitae ex. Suspendisse tincidunt tempor pharetra. Sed sed libero quis neque suscipit tristique et sed nunc. Suspendisse eleifend eleifend tempus. Ut eleifend nisl vel libero accumsan, id ultricies nisl faucibus. Maecenas gravida magna leo, vel porttitor leo pulvinar non. Nullam nunc mauris, aliquam id orci non, vestibulum bibendum felis. Ut finibus tellus sed sem blandit, a placerat sapien lacinia.

Quisque vitae risus in nisi semper suscipit. Etiam non tortor eget nibh mollis porta. Maecenas sed augue nunc. Donec at metus fringilla, tristique nibh ac, lobortis tellus. Duis pellentesque dolor ut nunc venenatis, lacinia rhoncus diam interdum. Nunc tempor turpis at felis egestas, vitae dictum velit pellentesque. Quisque scelerisque nisi eu sagittis placerat. Donec imperdiet posuere felis id commodo.

Vivamus feugiat consequat mauris, sit amet ultrices felis dignissim et. Donec accumsan elit eget sem scelerisque, at cursus metus convallis. Vestibulum hendrerit dolor odio, vitae pulvinar sem porta aliquam. Vestibulum eget interdum orci. Curabitur iaculis id lacus in commodo. Ut suscipit, sapien ac ultrices malesuada, sapien turpis sagittis metus, at aliquet leo tellus non nisl. Suspendisse vestibulum, tellus commodo efficitur ultrices, lectus turpis finibus augue, suscipit semper lectus augue ac magna. Cras ultricies lobortis leo, in efficitur urna tempus eu. Fusce feugiat, lacus vel aliquet condimentum, lacus mi accumsan dui, ultrices tempus leo nibh posuere est. Sed vitae enim nulla. Fusce posuere a quam at ultricies. Donec sed convallis turpis.

Ut posuere est in felis auctor pretium. Aliquam erat volutpat. Vivamus at lorem eu ante tristique dapibus at non enim. Fusce viverra fringilla interdum. Fusce non nisl sit amet mi dictum porttitor eget quis risus. Aliquam vel molestie mauris. Donec eget neque suscipit, consectetur erat quis, fermentum nulla. Aliquam sit amet interdum orci. Fusce faucibus bibendum orci in fringilla. Vestibulum ut varius mauris. Cras mauris ipsum, interdum placerat ligula vel, tincidunt sollicitudin nibh. Fusce lobortis non leo id imperdiet. In eu molestie nulla, quis placerat velit.

Vivamus dolor justo, posuere ac faucibus vitae, porttitor nec justo. Morbi pellentesque ex quis vehicula eleifend. Aliquam laoreet volutpat nunc, ac tristique augue gravida feugiat. Suspendisse sodales magna ac turpis tristique tempor. Integer libero diam, posuere in pharetra et, consectetur sed lectus. Curabitur quis augue a est sodales dictum. Cras consectetur metus non nisl tristique eleifend. Praesent sollicitudin in eros non elementum. Morbi vestibulum at nibh aliquet varius. Integer dapibus porttitor felis. Pellentesque eget quam semper, lobortis mi nec, maximus arcu. Nulla nec pulvinar turpis.

Phasellus cursus lacus at sem fermentum tincidunt. Nunc laoreet, metus vel dapibus ultrices, tortor nunc bibendum diam, eu blandit nisl dui at est. Phasellus sodales, tellus at maximus aliquam, libero felis congue est, quis posuere leo nisl quis odio. Quisque non ornare neque, sit amet euismod neque. Cras id est vel tellus ornare lobortis quis eu eros. Vivamus sed malesuada urna, et dictum velit. Ut molestie suscipit mi, ut vulputate ex porta at. Pellentesque eget sapien neque. Pellentesque dapibus porttitor nisl in fermentum. Nam mattis, eros at laoreet vehicula, orci magna ullamcorper mauris, eu interdum urna elit a erat. In interdum non dui vitae vulputate.

Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam et sollicitudin risus, non dictum neque. Pellentesque ultrices purus eu bibendum viverra. Praesent eget rutrum arcu. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed suscipit congue erat vitae dictum. Sed neque erat, viverra at mi non, tincidunt semper ante. Aenean at ante nulla. Sed gravida dolor eu tempus venenatis. Nam consequat mattis neque, pretium mattis metus. Phasellus nec scelerisque risus, id euismod massa. Curabitur malesuada feugiat augue non laoreet. Sed molestie sem et velit rutrum, in facilisis felis feugiat. Suspendisse potenti. In tincidunt, nunc nec fringilla hendrerit, ante arcu mattis magna, a eleifend tellus neque et enim."""
cantidad_vocales = contar_vocales(input_texto)
print(f"El texto contiene {cantidad_vocales} vocales.")